[package]
name = "pjproject-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]

[build-dependencies]
autotools = "0.2"
bindgen = "0.65.1"
pkg-config = "0.3"
tracing = "0.1"

[features]
default = [ "static" ]
static = []
